services:
  broker:
    build: ./MQTT
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped

volumes:
  mosquitto_data: